radar:
  menzil_km: 200.0
  tarama_hizi_hz: 0.5
  tespit_olasiligi: 0.4

batarya:
  muhimmat: 15
  vurus_hassasiyeti:
    yakin: 0.98
    orta: 0.85
    uzak: 0.55

tehdit_limitleri:
  kritik_hiz: 1200.0
  kritik_mesafe: 60.0
